export const CONFIG = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  APP_DOMAIN: 'APP_DOMAIN',
  APP_URI: 'APP_URI',
  CORS_ORIGIN: 'CORS_ORIGIN',
  JWT_SECRET: 'JWT_SECRET',
  JWT_DURATION: 'JWT_DURATION',
  SUPPORTED_CHAIN_IDS: 'SUPPORTED_CHAIN_IDS',
  DATABASE_URL: 'DATABASE_URL',
  DATABASE_AUTH_TOKEN: 'DATABASE_AUTH_TOKEN',
} as const;
