'use client'

import { motion, useInView } from 'framer-motion'
import { useRef } from 'react'
import { Key, Code2, FileCode, ExternalLink } from 'lucide-react'

const MARQUEE_ITEMS = [
  { label: 'ERC-20', sub: 'Fungible Token' },
  { label: 'ERC-721', sub: 'NFT Standard' },
  { label: 'ERC-1155', sub: 'Multi-Token' },
  { label: 'EIP-2612', sub: 'Permit' },
  { label: 'EIP-2981', sub: 'Royalties' },
  { label: 'EIP-3156', sub: 'Flash Loans' },
  { label: 'OpenZeppelin', sub: 'v5 Contracts' },
  { label: 'Hardhat', sub: 'Compatible' },
  { label: 'Foundry', sub: 'Compatible' },
  { label: 'Remix IDE', sub: 'Compatible' },
  { label: 'Solidity', sub: '^0.8.24' },
  { label: 'NatSpec', sub: 'Documented' },
]

const TRUST_POINTS = [
  {
    icon: Key,
    title: 'Your code. Full stop.',
    description: "Everything generated by Vesper is yours. No licenses, no attribution requirements, no strings attached. Download it and it's gone — we don't store it, we don't log it.",
    accent: 'hsl(174 72% 50%)',
  },
  {
    icon: Code2,
    title: 'Open, readable output.',
    description: "The generated code is written to be read by humans — not minified, not obfuscated. Every function is documented. Every import is explicit. You always know exactly what you're deploying.",
    accent: 'hsl(199 89% 55%)',
  },
  {
    icon: FileCode,
    title: 'Standards, not reinvention.',
    description: "We don't write custom token logic. We don't implement our own AccessControl. Vesper wires together audited, widely-used OpenZeppelin primitives in the correct, documented way.",
    accent: 'hsl(262 80% 65%)',
  },
]

function MarqueeTrack({ reverse = false }: { reverse?: boolean }) {
  const doubled = [...MARQUEE_ITEMS, ...MARQUEE_ITEMS]
  return (
    <div className="flex overflow-hidden">
      <motion.div
        className="flex gap-3 shrink-0"
        animate={{ x: reverse ? ['0%', '50%'] : ['0%', '-50%'] }}
        transition={{ duration: 30, repeat: Infinity, ease: 'linear' }}
      >
        {doubled.map((item, i) => (
          <div
            key={i}
            className="glass-card rounded-xl px-5 py-3 shrink-0 flex items-center gap-3 border-border/30"
          >
            <div className="w-1.5 h-1.5 rounded-full bg-primary/60 shrink-0" />
            <div>
              <div className="text-sm font-semibold text-foreground/90 whitespace-nowrap">{item.label}</div>
              <div className="text-[10px] text-muted-foreground/60 font-mono whitespace-nowrap">{item.sub}</div>
            </div>
          </div>
        ))}
      </motion.div>
    </div>
  )
}

export default function TrustSection() {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-80px' })

  return (
    <section id="trust" ref={ref} className="relative py-28 overflow-hidden">
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-px h-24 bg-gradient-to-b from-transparent via-primary/30 to-transparent" />

      {/* Marquee — full bleed */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={inView ? { opacity: 1 } : {}}
        transition={{ duration: 0.8 }}
        className="space-y-3 mb-20"
      >
        {/* Fade masks */}
        <div className="relative">
          <div className="absolute left-0 top-0 bottom-0 w-24 z-10 pointer-events-none bg-gradient-to-r from-background to-transparent" />
          <div className="absolute right-0 top-0 bottom-0 w-24 z-10 pointer-events-none bg-gradient-to-l from-background to-transparent" />
          <MarqueeTrack />
        </div>
        <div className="relative">
          <div className="absolute left-0 top-0 bottom-0 w-24 z-10 pointer-events-none bg-gradient-to-r from-background to-transparent" />
          <div className="absolute right-0 top-0 bottom-0 w-24 z-10 pointer-events-none bg-gradient-to-l from-background to-transparent" />
          <MarqueeTrack reverse />
        </div>
      </motion.div>

      {/* Trust points */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5 }}
          className="mb-14"
        >
          <p className="text-primary text-xs font-mono uppercase tracking-[0.2em] mb-3">Trust & transparency</p>
          <h2 className="text-3xl md:text-4xl font-bold tracking-tight">
            You own what you build.<br />
            <span className="gradient-text">We just help you build it.</span>
          </h2>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {TRUST_POINTS.map((point, i) => {
            const Icon = point.icon
            return (
              <motion.div
                key={point.title}
                initial={{ opacity: 0, y: 24 }}
                animate={inView ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                className="glass-card rounded-2xl p-6 group hover:border-white/10 transition-all duration-300 relative overflow-hidden"
              >
                <div
                  className="absolute -bottom-10 -right-10 w-32 h-32 rounded-full blur-2xl pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-300"
                  style={{ background: `${point.accent}12` }}
                />
                <div
                  className="w-10 h-10 rounded-lg flex items-center justify-center mb-5 transition-transform duration-300 group-hover:scale-110"
                  style={{ background: `${point.accent}12`, border: `1px solid ${point.accent}20` }}
                >
                  <Icon size={18} style={{ color: point.accent }} />
                </div>
                <h3 className="font-semibold mb-3">{point.title}</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">{point.description}</p>
              </motion.div>
            )
          })}
        </div>

        {/* Bottom footnote */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={inView ? { opacity: 1 } : {}}
          transition={{ duration: 0.5, delay: 0.4 }}
          className="mt-10 flex items-center justify-center gap-2 text-xs text-muted-foreground/40 font-mono"
        >
          <ExternalLink size={11} />
          <span>Built on OpenZeppelin Contracts v5 — the most-used smart contract library in existence</span>
        </motion.div>
      </div>
    </section>
  )
}
