import type {
  ContractGenerator,
  ContractParts,
  FeatureMixin,
} from '@vesper/types';
import { royaltiesMixin } from './shared';

// ═════════════════════════════════════════════════════════════════════════════
// ERC-1155
// ═════════════════════════════════════════════════════════════════════════════

const erc1155Mintable: FeatureMixin = {
  id: 'mintable',
  apply(parts) {
    parts.errors.push({ source: 'error ZeroAddress();' });
    parts.errors.push({ source: 'error ArrayLengthMismatch();' });

    parts.functions.push({
      source: `/**
 * @notice Mint \`amount\` of token \`id\` to \`to\`.
 * @param to     Recipient address.
 * @param id     Token identifier.
 * @param amount Number of tokens to mint.
 * @param data   Additional data passed to receiver hooks.
 */
function mint(
    address to,
    uint256 id,
    uint256 amount,
    bytes memory data
) external onlyOwner {
    if (to == address(0)) revert ZeroAddress();
    _mint(to, id, amount, data);
}

/**
 * @notice Batch mint multiple token ids in one transaction.
 * @param to      Recipient address.
 * @param ids     Array of token identifiers.
 * @param amounts Array of token amounts (must match ids length).
 * @param data    Additional data passed to receiver hooks.
 */
function mintBatch(
    address to,
    uint256[] memory ids,
    uint256[] memory amounts,
    bytes memory data
) external onlyOwner {
    if (to == address(0)) revert ZeroAddress();
    if (ids.length != amounts.length) revert ArrayLengthMismatch();
    _mintBatch(to, ids, amounts, data);
}`,
    });
  },
};

const erc1155Burnable: FeatureMixin = {
  id: 'burnable',
  apply(parts) {
    parts.imports.push({
      path: '@openzeppelin/contracts/token/ERC1155/extensions/ERC1155Burnable.sol',
      symbol: 'ERC1155Burnable',
    });
    parts.inheritances.push('ERC1155Burnable');
  },
};

const erc1155Supply: FeatureMixin = {
  id: 'supply',
  apply(parts) {
    parts.imports.push({
      path: '@openzeppelin/contracts/token/ERC1155/extensions/ERC1155Supply.sol',
      symbol: 'ERC1155Supply',
    });
    parts.inheritances.push('ERC1155Supply');

    parts.functions.push({
      source: `/// @inheritdoc ERC1155
function _update(
    address from,
    address to,
    uint256[] memory ids,
    uint256[] memory values
) internal override(ERC1155, ERC1155Supply) {
    super._update(from, to, ids, values);
}`,
    });
  },
};

const erc1155Pausable: FeatureMixin = {
  id: 'pausable',
  apply(parts, ctx) {
    parts.imports.push({
      path: '@openzeppelin/contracts/token/ERC1155/extensions/ERC1155Pausable.sol',
      symbol: 'ERC1155Pausable',
    });
    parts.inheritances.push('ERC1155Pausable');

    const supplyOverride = ctx.hasFeature('supply') ? ', ERC1155Supply' : '';

    parts.functions.push({
      source: `/// @inheritdoc ERC1155
function _update(
    address from,
    address to,
    uint256[] memory ids,
    uint256[] memory values
) internal override(ERC1155, ERC1155Pausable${supplyOverride}) {
    super._update(from, to, ids, values);
}

/**
 * @notice Pause all token transfers.
 */
function pause() external onlyOwner { _pause(); }

/**
 * @notice Resume all token transfers.
 */
function unpause() external onlyOwner { _unpause(); }`,
    });
  },
};
const type = 'erc1155';

export const erc1155Generator: ContractGenerator = {
  type: type,

  baseParts(ctx): ContractParts {
    const { name, description } = ctx.config;
    return {
      license: ctx.config.license ?? 'MIT',
      solidityVersion: ctx.config.solidityVersion ?? '^0.8.24',
      imports: [
        {
          path: '@openzeppelin/contracts/token/ERC1155/ERC1155.sol',
          symbol: 'ERC1155',
        },
      ],
      inheritances: ['ERC1155'],
      natspecTitle: name,
      natspecNotice:
        description ?? `${name} — an ERC-1155 multi-token contract.`,
      natspecDev: 'Generated by Vesper. Review before production use.',
      stateVariables: [],
      events: [],
      errors: [],
      modifiers: [],
      constructorArgs: [
        {
          type: 'string memory',
          name: '_uri',
          comment:
            'Base metadata URI, e.g. https://api.example.com/metadata/{id}.json',
        },
      ],
      constructorNatspec: [
        '@notice Deploy the contract with a base metadata URI.',
        '@param _uri Base metadata URI.',
      ],
      constructorInitializers: ['ERC1155(_uri)'],
      constructorBody: [],
      functions: [
        {
          source: `/**
 * @notice Update the metadata URI. Only callable by owner.
 * @param newUri New base metadata URI.
 */
function setURI(string memory newUri) external onlyOwner {
    _setURI(newUri);
}

/// @inheritdoc ERC1155
function supportsInterface(bytes4 interfaceId)
    public
    view
    override(ERC1155)
    returns (bool)
{
    return super.supportsInterface(interfaceId);
}`,
        },
      ],
    };
  },
  mixins: [
    erc1155Mintable,
    erc1155Burnable,
    erc1155Supply,
    erc1155Pausable,
    { ...royaltiesMixin },
  ],
};
