import type {
  ContractGenerator,
  ContractParts,
  FeatureMixin,
} from '@vesper/types';

// ═════════════════════════════════════════════════════════════════════════════
// Multi-Sig
// ═════════════════════════════════════════════════════════════════════════════

const multisigTimelocked: FeatureMixin = {
  id: 'timelocked',
  apply(parts) {
    parts.stateVariables.push({
      visibility: 'public',
      type: 'uint256',
      name: 'timelockDelay',
      comment: 'Seconds between confirmation and execution.',
    });
    parts.stateVariables.push({
      visibility: 'public',
      type: 'mapping(uint256 => uint256)',
      name: 'executionTime',
      comment: 'Earliest timestamp a confirmed tx can be executed.',
    });

    parts.constructorArgs.push({
      type: 'uint256',
      name: '_timelockDelay',
      comment: 'Delay in seconds',
    });
    parts.constructorBody.push('timelockDelay = _timelockDelay;');

    parts.errors.push({
      source: 'error TimelockNotExpired(uint256 executionTime);',
    });
  },
};

const multisigBatching: FeatureMixin = {
  id: 'batching',
  apply(parts) {
    parts.functions.push({
      source: `/**
 * @notice Submit multiple transactions as a single batch.
 * @param targets   Array of target addresses.
 * @param values    Array of ETH values.
 * @param datas     Array of calldata payloads.
 */
function submitBatch(
    address[] memory targets,
    uint256[] memory values,
    bytes[] memory datas
) external onlyOwner returns (uint256 txIndex) {
    uint256 len = targets.length;
    require(len == values.length && len == datas.length, "Length mismatch");
    for (uint256 i; i < len; ++i) {
        txIndex = _submitTransaction(targets[i], values[i], datas[i]);
    }
}`,
    });
  },
};

const type = 'multisig';

export const multisigGenerator: ContractGenerator = {
  type: type,

  baseParts(ctx): ContractParts {
    const { name, description } = ctx.config;
    const hasTimelock = ctx.hasFeature('timelocked');

    return {
      license: ctx.config.license ?? 'MIT',
      solidityVersion: ctx.config.solidityVersion ?? '^0.8.24',
      imports: [
        {
          path: '@openzeppelin/contracts/utils/ReentrancyGuard.sol',
          symbol: 'ReentrancyGuard',
        },
      ],
      inheritances: ['ReentrancyGuard'],
      natspecTitle: name,
      natspecNotice: description ?? `${name} — M-of-N multi-signature wallet.`,
      natspecDev:
        'Generated by Vesper. Audit before holding significant funds.',
      stateVariables: [
        {
          visibility: 'public',
          type: 'address[]',
          name: 'owners',
          comment: 'List of owner addresses.',
        },
        {
          visibility: 'public',
          type: 'mapping(address => bool)',
          name: 'isOwner',
          comment: 'Quick owner lookup.',
        },
        {
          visibility: 'public',
          type: 'uint256',
          name: 'required',
          comment: 'Number of confirmations required to execute.',
        },
      ],
      events: [
        {
          source:
            'event Deposit(address indexed sender, uint256 amount, uint256 balance);',
        },
        {
          source:
            'event SubmitTransaction(address indexed owner, uint256 indexed txIndex, address indexed to, uint256 value, bytes data);',
        },
        {
          source:
            'event ConfirmTransaction(address indexed owner, uint256 indexed txIndex);',
        },
        {
          source:
            'event RevokeConfirmation(address indexed owner, uint256 indexed txIndex);',
        },
        {
          source:
            'event ExecuteTransaction(address indexed owner, uint256 indexed txIndex);',
        },
      ],
      errors: [
        { source: 'error NotOwner();' },
        { source: 'error TxDoesNotExist();' },
        { source: 'error TxAlreadyExecuted();' },
        { source: 'error TxAlreadyConfirmed();' },
        { source: 'error TxNotConfirmed();' },
        { source: 'error InsufficientConfirmations();' },
        { source: 'error ExecutionFailed();' },
        { source: 'error InvalidOwnerConfig();' },
      ],
      modifiers: [
        {
          source: `modifier onlyOwner() {\n    if (!isOwner[msg.sender]) revert NotOwner();\n    _;\n}`,
        },
        {
          source: `modifier txExists(uint256 txIndex) {\n    if (txIndex >= transactions.length) revert TxDoesNotExist();\n    _;\n}`,
        },
        {
          source: `modifier notExecuted(uint256 txIndex) {\n    if (transactions[txIndex].executed) revert TxAlreadyExecuted();\n    _;\n}`,
        },
        {
          source: `modifier notConfirmed(uint256 txIndex) {\n    if (isConfirmed[txIndex][msg.sender]) revert TxAlreadyConfirmed();\n    _;\n}`,
        },
      ],
      constructorArgs: [
        {
          type: 'address[]',
          name: '_owners',
          comment: 'Initial owner addresses',
        },
        {
          type: 'uint256',
          name: '_required',
          comment: 'Number of required confirmations',
        },
      ],
      constructorNatspec: [
        '@notice Deploy with an initial owner set and confirmation threshold.',
        '@param _owners   Array of owner addresses. No duplicates or zero addresses.',
        '@param _required Number of confirmations required (must be > 0 and <= owners.length).',
      ],
      constructorInitializers: [],
      constructorBody: [
        'if (_owners.length == 0) revert InvalidOwnerConfig();',
        'if (_required == 0 || _required > _owners.length) revert InvalidOwnerConfig();',
        'for (uint256 i; i < _owners.length; ++i) {',
        '    address owner = _owners[i];',
        '    if (owner == address(0)) revert InvalidOwnerConfig();',
        '    if (isOwner[owner]) revert InvalidOwnerConfig();',
        '    isOwner[owner] = true;',
        '    owners.push(owner);',
        '}',
        'required = _required;',
      ],
      functions: [
        {
          source: `struct Transaction {
    address to;
    uint256 value;
    bytes data;
    bool executed;
    uint256 numConfirmations;
}

Transaction[] public transactions;
mapping(uint256 => mapping(address => bool)) public isConfirmed;

receive() external payable {
    emit Deposit(msg.sender, msg.value, address(this).balance);
}

/**
 * @notice Submit a new transaction for confirmation.
 * @param _to   Target contract or EOA.
 * @param _value ETH to send with the call.
 * @param _data  ABI-encoded calldata.
 * @return txIndex Index of the newly submitted transaction.
 */
function submitTransaction(address _to, uint256 _value, bytes memory _data)
    external
    onlyOwner
    returns (uint256 txIndex)
{
    return _submitTransaction(_to, _value, _data);
}

function _submitTransaction(address _to, uint256 _value, bytes memory _data)
    internal
    returns (uint256 txIndex)
{
    txIndex = transactions.length;
    transactions.push(Transaction({ to: _to, value: _value, data: _data, executed: false, numConfirmations: 0 }));
    emit SubmitTransaction(msg.sender, txIndex, _to, _value, _data);
}

/**
 * @notice Confirm a pending transaction.
 * @param txIndex Index of the transaction to confirm.
 */
function confirmTransaction(uint256 txIndex)
    external
    onlyOwner
    txExists(txIndex)
    notExecuted(txIndex)
    notConfirmed(txIndex)
{
    Transaction storage txn = transactions[txIndex];
    txn.numConfirmations += 1;
    isConfirmed[txIndex][msg.sender] = true;${
      hasTimelock
        ? `
    // Start timelock on first confirmation reaching threshold
    if (txn.numConfirmations == required) {
        executionTime[txIndex] = block.timestamp + timelockDelay;
    }`
        : ''
    }
    emit ConfirmTransaction(msg.sender, txIndex);
}

/**
 * @notice Execute a fully confirmed transaction.
 * @param txIndex Index of the transaction to execute.
 */
function executeTransaction(uint256 txIndex)
    external
    onlyOwner
    txExists(txIndex)
    notExecuted(txIndex)
    nonReentrant
{
    Transaction storage txn = transactions[txIndex];
    if (txn.numConfirmations < required) revert InsufficientConfirmations();${
      hasTimelock
        ? `
    if (block.timestamp < executionTime[txIndex]) revert TimelockNotExpired(executionTime[txIndex]);`
        : ''
    }
    txn.executed = true;
    (bool success, ) = txn.to.call{ value: txn.value }(txn.data);
    if (!success) revert ExecutionFailed();
    emit ExecuteTransaction(msg.sender, txIndex);
}

/**
 * @notice Revoke your confirmation for a pending transaction.
 * @param txIndex Index of the transaction.
 */
function revokeConfirmation(uint256 txIndex)
    external
    onlyOwner
    txExists(txIndex)
    notExecuted(txIndex)
{
    if (!isConfirmed[txIndex][msg.sender]) revert TxNotConfirmed();
    Transaction storage txn = transactions[txIndex];
    txn.numConfirmations -= 1;
    isConfirmed[txIndex][msg.sender] = false;
    emit RevokeConfirmation(msg.sender, txIndex);
}

/// @notice Returns the total number of submitted transactions.
function getTransactionCount() external view returns (uint256) {
    return transactions.length;
}

/// @notice Returns all owner addresses.
function getOwners() external view returns (address[] memory) {
    return owners;
}`,
        },
      ],
    };
  },
  mixins: [multisigTimelocked, multisigBatching],
};
