import type {
  ContractGenerator,
  ContractParts,
  FeatureMixin,
} from "@vesper/types"
import { getContractTemplate } from "../helpers"

// ═════════════════════════════════════════════════════════════════════════════
// Staking
// ═════════════════════════════════════════════════════════════════════════════

const stakingLockPeriod: FeatureMixin = {
  id: 'lock-period',
  apply(parts, _ctx) {
    parts.stateVariables.push({
      visibility: 'public',
      type: 'uint256',
      name: 'lockDuration',
      comment: 'Minimum seconds a stake must remain locked before withdrawal.',
    })
    parts.stateVariables.push({
      visibility: 'public',
      type: 'mapping(address => uint256)',
      name: 'stakeTimestamp',
      comment: 'Timestamp when each address last staked.',
    })

    parts.constructorArgs.push({
      type: 'uint256',
      name: '_lockDuration',
      comment: 'Lock period in seconds',
    })
    parts.constructorBody.push('lockDuration = _lockDuration;')

    parts.errors.push({ source: 'error LockPeriodActive(uint256 unlockTime);' })
    parts.events.push({ source: 'event LockDurationUpdated(uint256 oldDuration, uint256 newDuration);' })

    parts.functions.push({
      source: `/**
 * @notice Update the lock duration. Only affects new stakes.
 * @param newDuration New lock duration in seconds.
 */
function setLockDuration(uint256 newDuration) external onlyOwner {
    emit LockDurationUpdated(lockDuration, newDuration);
    lockDuration = newDuration;
}`,
    })
  },
}

const stakingEmergencyWithdraw: FeatureMixin = {
  id: 'emergency-withdraw',
  apply(parts, _ctx) {
    parts.stateVariables.push({
      visibility: 'public',
      type: 'uint256',
      name: 'emergencyPenaltyBps',
      initialValue: '1000',
      comment: 'Penalty in basis points for emergency withdrawal (default 10%).',
    })

    parts.errors.push({ source: 'error InvalidPenalty();' })
    parts.events.push({ source: 'event EmergencyWithdraw(address indexed user, uint256 amount, uint256 penalty);' })

    parts.functions.push({
      source: `/**
 * @notice Emergency withdraw without waiting for the lock period.
 *         A penalty is deducted and sent to the contract owner.
 */
function emergencyWithdraw() external nonReentrant {
    uint256 amount = staked[msg.sender];
    require(amount > 0, "Nothing staked");
    uint256 penalty = (amount * emergencyPenaltyBps) / 10_000;
    uint256 payout = amount - penalty;

    totalStaked -= amount;
    staked[msg.sender] = 0;
    rewards[msg.sender] = 0;

    stakingToken.transfer(owner(), penalty);
    stakingToken.transfer(msg.sender, payout);

    emit EmergencyWithdraw(msg.sender, payout, penalty);
}

/**
 * @notice Update the emergency withdrawal penalty. Max 50%.
 */
function setEmergencyPenalty(uint256 newBps) external onlyOwner {
    if (newBps > 5_000) revert InvalidPenalty();
    emergencyPenaltyBps = newBps;
}`,
    })
  },
}

const type  = "staking"
const contractTemplate = getContractTemplate(type)

export const stakingGenerator: ContractGenerator = {
  type: type,
  availableFeatures: contractTemplate?.availableFeatures ?? [],
  defaultFeatures: contractTemplate?.defaultFeatures ?? [],

  baseParts(ctx): ContractParts {
    const { name, description } = ctx.config
    return {
      license: ctx.config.license ?? 'MIT',
      solidityVersion: ctx.config.solidityVersion ?? '^0.8.24',
      imports: [
        { path: '@openzeppelin/contracts/token/ERC20/IERC20.sol', symbol: 'IERC20' },
        { path: '@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol', symbol: 'SafeERC20' },
        { path: '@openzeppelin/contracts/utils/ReentrancyGuard.sol', symbol: 'ReentrancyGuard' },
      ],
      inheritances: ['ReentrancyGuard'],
      natspecTitle: name,
      natspecNotice: description ?? `${name} — stake tokens to earn rewards.`,
      natspecDev: 'Uses pull-based reward pattern. Generated by Vesper.',
      stateVariables: [
        { visibility: 'public', type: 'IERC20', name: 'stakingToken', comment: 'Token users stake.' },
        { visibility: 'public', type: 'IERC20', name: 'rewardToken', comment: 'Token distributed as rewards.' },
        { visibility: 'public', type: 'uint256', name: 'rewardRate', comment: 'Reward tokens distributed per second.' },
        { visibility: 'public', type: 'uint256', name: 'rewardsDuration', comment: 'Duration of the current reward period in seconds.' },
        { visibility: 'public', type: 'uint256', name: 'periodFinish', comment: 'Timestamp when current reward period ends.' },
        { visibility: 'public', type: 'uint256', name: 'lastUpdateTime', comment: 'Last time rewards were updated.' },
        { visibility: 'public', type: 'uint256', name: 'rewardPerTokenStored', comment: 'Accumulated reward per staked token.' },
        { visibility: 'public', type: 'uint256', name: 'totalStaked', comment: 'Total tokens currently staked.' },
        { visibility: 'public', type: 'mapping(address => uint256)', name: 'staked', comment: 'Amount staked per address.' },
        { visibility: 'public', type: 'mapping(address => uint256)', name: 'rewards', comment: 'Pending rewards per address.' },
        { visibility: 'private', type: 'mapping(address => uint256)', name: 'userRewardPerTokenPaid', comment: 'Last reward snapshot per address.' },
      ],
      events: [
        { source: 'event Staked(address indexed user, uint256 amount);' },
        { source: 'event Withdrawn(address indexed user, uint256 amount);' },
        { source: 'event RewardPaid(address indexed user, uint256 reward);' },
        { source: 'event RewardAdded(uint256 reward, uint256 duration);' },
      ],
      errors: [
        { source: 'error ZeroAmount();' },
        { source: 'error RewardPeriodNotFinished();' },
        { source: 'error InsufficientRewardBalance();' },
      ],
      modifiers: [
        {
          source: `modifier updateReward(address account) {
    rewardPerTokenStored = rewardPerToken();
    lastUpdateTime = lastTimeRewardApplicable();
    if (account != address(0)) {
        rewards[account] = earned(account);
        userRewardPerTokenPaid[account] = rewardPerTokenStored;
    }
    _;
}`,
        },
      ],
      constructorArgs: [
        { type: 'address', name: '_stakingToken', comment: 'Address of the token to stake' },
        { type: 'address', name: '_rewardToken', comment: 'Address of the reward token' },
      ],
      constructorNatspec: [
        '@notice Deploy the staking contract.',
        '@param _stakingToken ERC-20 token users will stake.',
        '@param _rewardToken  ERC-20 token distributed as rewards.',
      ],
      constructorInitializers: [],
      constructorBody: [
        'require(_stakingToken != address(0) && _rewardToken != address(0), "Zero address");',
        'stakingToken = IERC20(_stakingToken);',
        'rewardToken = IERC20(_rewardToken);',
        'rewardsDuration = 7 days;',
      ],
      functions: [
        {
          source: `/// @notice Returns the applicable reward timestamp (now or period end, whichever is earlier).
function lastTimeRewardApplicable() public view returns (uint256) {
    return block.timestamp < periodFinish ? block.timestamp : periodFinish;
}

/// @notice Returns accumulated reward per staked token.
function rewardPerToken() public view returns (uint256) {
    if (totalStaked == 0) return rewardPerTokenStored;
    return rewardPerTokenStored + (
        (lastTimeRewardApplicable() - lastUpdateTime) * rewardRate * 1e18 / totalStaked
    );
}

/**
 * @notice Returns the total rewards earned by \`account\`.
 * @param account The address to query.
 */
function earned(address account) public view returns (uint256) {
    return (staked[account] * (rewardPerToken() - userRewardPerTokenPaid[account])) / 1e18
        + rewards[account];
}

/**
 * @notice Stake \`amount\` tokens. Caller must approve this contract first.
 * @param amount Number of tokens to stake.
 */
function stake(uint256 amount) external nonReentrant updateReward(msg.sender) {
    if (amount == 0) revert ZeroAmount();
    totalStaked += amount;
    staked[msg.sender] += amount;${ctx.hasFeature('lock-period') ? '\n    stakeTimestamp[msg.sender] = block.timestamp;' : ''}
    SafeERC20.safeTransferFrom(stakingToken, msg.sender, address(this), amount);
    emit Staked(msg.sender, amount);
}

/**
 * @notice Withdraw \`amount\` staked tokens.
 * @param amount Number of tokens to withdraw.
 */
function withdraw(uint256 amount) external nonReentrant updateReward(msg.sender) {
    if (amount == 0) revert ZeroAmount();
    require(staked[msg.sender] >= amount, "Insufficient stake");${ctx.hasFeature('lock-period') ? `
    if (block.timestamp < stakeTimestamp[msg.sender] + lockDuration) {
        revert LockPeriodActive(stakeTimestamp[msg.sender] + lockDuration);
    }` : ''}
    totalStaked -= amount;
    staked[msg.sender] -= amount;
    SafeERC20.safeTransfer(stakingToken, msg.sender, amount);
    emit Withdrawn(msg.sender, amount);
}

/**
 * @notice Claim all pending rewards.
 */
function getReward() external nonReentrant updateReward(msg.sender) {
    uint256 reward = rewards[msg.sender];
    if (reward > 0) {
        rewards[msg.sender] = 0;
        SafeERC20.safeTransfer(rewardToken, msg.sender, reward);
        emit RewardPaid(msg.sender, reward);
    }
}

/**
 * @notice Fund a new reward period. Only callable by owner.
 * @param reward Total reward tokens to distribute over the duration.
 */
function notifyRewardAmount(uint256 reward) external onlyOwner updateReward(address(0)) {
    if (block.timestamp < periodFinish) revert RewardPeriodNotFinished();
    rewardRate = reward / rewardsDuration;
    require(rewardToken.balanceOf(address(this)) >= rewardRate * rewardsDuration, "Insufficient reward balance");
    lastUpdateTime = block.timestamp;
    periodFinish = block.timestamp + rewardsDuration;
    emit RewardAdded(reward, rewardsDuration);
}

/**
 * @notice Update reward distribution duration. Only callable by owner when no period is active.
 */
function setRewardsDuration(uint256 _rewardsDuration) external onlyOwner {
    if (block.timestamp < periodFinish) revert RewardPeriodNotFinished();
    rewardsDuration = _rewardsDuration;
}`,
        },
      ],
    }
  },
  mixins: [stakingLockPeriod, stakingEmergencyWithdraw],
}
